//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  DESKTOP-AOQBD56
//  DateTime: 07.09.2024 18:23:27
//  UserName: Paulsams
//  GPLEX input file <ParserGenerator\SpecFiles\gppg.lex - 07.09.2024 18:23:26>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, parser, stack, minimize
//  Option settings: classes, compressMap, compressNext, persistBuffer, noEmbedBuffers
//  Fallback code page: Raw 8-bit binary
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define LEFTANCHORS
#define STACK
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;

using QUT.GplexBuffers;
using System.Collections;
using QUT.GPGen.Parser;

namespace QUT.GPGen.Lexers
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     internal enum Token
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     internal abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     internal interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     internal sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     internal sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Token).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 99;
        const int initial = 100;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int TheRules = 1;
        const int TheEpilog = 2;
        const int GetPath = 3;
        const int Prolog = 4;
        const int Action = 5;
        const int Comment = 6;
        const int CodeBlock = 7;
        const int ShouldBeBlank = 8;

#region user code
/* gppg.lex: Author: John Gough, August 2008 */
/* 
 * Expected file format is Unicode. In the event that no 
 * byte order mark prefix is found, revert to raw bytes.
 */
/* --------------------------- */
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {100, 119, 137, 140, 137, 146, 
        74, 147, 166, 0};

   static int[] anchorState = new int[] {101, 120, 137, 140, 145, 146, 
        74, 148, 166, 0};

#region CompressedCharacterMap
    //
    // There are 36 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 126 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[126] {
/*     '\0' */ 5, 24, 24, 24, 24, 24, 24, 5, 5, 2, 0, 5, 5, 4, 24, 24, 
/*   '\x10' */ 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
/*   '\x20' */ 23, 24, 29, 24, 24, 6, 24, 22, 31, 32, 3, 24, 30, 24, 30, 1, 
/*      '0' */ 19, 26, 26, 26, 26, 26, 26, 26, 9, 9, 30, 30, 30, 34, 30, 24, 
/*      '@' */ 33, 21, 21, 21, 21, 21, 10, 8, 8, 8, 8, 8, 8, 8, 8, 15, 
/*      'P' */ 8, 8, 8, 8, 8, 28, 8, 8, 8, 8, 8, 30, 25, 30, 24, 8, 
/*      '`' */ 24, 21, 21, 21, 14, 12, 16, 8, 8, 11, 8, 8, 13, 8, 8, 8, 
/*      'p' */ 8, 8, 8, 17, 18, 27, 8, 8, 20, 8, 8, 7, 30, 35 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 126) // '\0' <= code <= '}'
        return mapC0[code - 0];
      else // '~' <= code <= '\U0010FFFF'
        return (sbyte)24;
    }
#endregion

    static Table[] NxS = new Table[167] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {32, -1, 33}),
/* NxS[   2] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[   3] */ // Shortest string "^%"
      new Table(19, 27, 30, new short[] {27, 30, 30, 27, -1, 27, 
          27, 27, 30, 30, 27, 27, 27, 27, 27, 27, 31, -1, 27, -1, 27, -1, 
          27, 28, 29, 30, 27}),
/* NxS[   4] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[   5] */ // Shortest string "G"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[   6] */ // Shortest string "8"
      new Table(9, 18, -1, new short[] {6, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 6, -1, -1, -1, -1, -1, -1, 6}),
/* NxS[   7] */ // Shortest string "F"
      new Table(8, 21, -1, new short[] {5, 5, 5, 17, 5, 5, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[   8] */ // Shortest string "0"
      new Table(9, 18, -1, new short[] {6, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 6, 118, -1, -1, -1, -1, -1, 6}),
/* NxS[   9] */ // Shortest string "'"
      new Table(22, 20, 104, new short[] {-1, 104, 104, 105, 104, 104, 
          104, 104, 104, 104, 104, 104, 104, 104, -1, 104, -1, 104, -1, -1}),
/* NxS[  10] */ // Shortest string "\""
      new Table(25, 17, 102, new short[] {103, 102, 102, 102, 14, 102, 
          102, 102, 102, 102, 102, 13, 102, -1, 102, 13, -1}),
/* NxS[  11] */ new Table(0, 0, -1, null), // Shortest string "("
/* NxS[  12] */ new Table(0, 0, -1, null), // Shortest string ")"
/* NxS[  13] */ new Table(0, 0, -1, null), // Shortest string "\"\r"
/* NxS[  14] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  15] */ new Table(0, 0, -1, null), // Shortest string "'/'"
/* NxS[  16] */ // Shortest string "0x8"
      new Table(9, 18, -1, new short[] {16, 16, -1, 16, -1, 16, 
          -1, 16, -1, -1, 16, -1, 16, -1, -1, -1, -1, 16}),
/* NxS[  17] */ // Shortest string "Fi"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 18, 5, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  18] */ // Shortest string "Fie"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 19, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  19] */ // Shortest string "Fiel"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          20, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  20] */ // Shortest string "Field"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 21, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  21] */ // Shortest string "FieldO"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 22, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  22] */ // Shortest string "FieldOf"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 23, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  23] */ // Shortest string "FieldOff"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 5, 24, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  24] */ // Shortest string "FieldOffs"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 25, 5, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  25] */ // Shortest string "FieldOffse"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 5, 5, 26, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  26] */ // Shortest string "FieldOffset"
      new Table(8, 21, -1, new short[] {5, 5, 5, 5, 5, 5, 
          5, 5, 5, 5, 5, 5, 5, 5, -1, -1, -1, -1, 5, 5, 5}),
/* NxS[  27] */ new Table(0, 0, -1, null), // Shortest string "%/"
/* NxS[  28] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  29] */ new Table(0, 0, -1, null), // Shortest string "^%{"
/* NxS[  30] */ // Shortest string "^%G"
      new Table(8, 21, -1, new short[] {30, 30, 30, 30, 30, 30, 
          30, 30, 30, 30, 30, 30, 30, 30, -1, -1, -1, -1, 30, 30, 30}),
/* NxS[  31] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  32] */ // Shortest string "//"
      new Table(0, 5, 32, new short[] {-1, 32, 32, 32, -1}),
/* NxS[  33] */ new Table(0, 0, -1, null), // Shortest string "/*"
/* NxS[  34] */ // Shortest string "%"
      new Table(19, 27, 35, new short[] {27, 35, 35, 27, -1, 27, 
          27, 27, 35, 35, 27, 27, 27, 27, 27, 27, 27, -1, 27, -1, 27, -1, 
          27, 27, 27, 35, 27}),
/* NxS[  35] */ // Shortest string "%G"
      new Table(8, 21, -1, new short[] {35, 35, 35, 35, 35, 35, 
          35, 35, 35, 35, 35, 35, 35, 35, -1, -1, -1, -1, 35, 35, 35}),
/* NxS[  36] */ // Shortest string "^%"
      new Table(19, 27, 45, new short[] {27, 45, 45, 27, -1, 27, 
          27, 27, 45, 45, 27, 27, 27, 27, 27, 27, 31, -1, 27, -1, 27, -1, 
          27, 44, 27, 45, 27}),
/* NxS[  37] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  38] */ // Shortest string "^G"
      new Table(8, 21, -1, new short[] {38, 38, 38, 38, 38, 38, 
          38, 38, 38, 38, 38, 38, 38, 38, -1, -1, -1, -1, 38, 38, 38}),
/* NxS[  39] */ // Shortest string "'"
      new Table(22, 20, 123, new short[] {-1, 123, 123, 124, 123, 123, 
          123, 123, 123, 123, 123, 123, 123, 123, -1, 123, -1, 123, -1, -1}),
/* NxS[  40] */ // Shortest string "\""
      new Table(25, 17, 121, new short[] {122, 121, 121, 121, 42, 121, 
          121, 121, 121, 121, 121, 13, 121, -1, 121, 13, -1}),
/* NxS[  41] */ new Table(0, 0, -1, null), // Shortest string ","
/* NxS[  42] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  43] */ new Table(0, 0, -1, null), // Shortest string "'/'"
/* NxS[  44] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  45] */ // Shortest string "%G"
      new Table(8, 21, -1, new short[] {45, 45, 45, 45, 45, 45, 
          45, 45, 45, 45, 45, 45, 45, 45, -1, -1, -1, -1, 45, 45, 45}),
/* NxS[  46] */ // Shortest string "%"
      new Table(19, 27, 45, new short[] {27, 45, 45, 27, -1, 27, 
          27, 27, 45, 45, 27, 27, 27, 27, 27, 27, 27, -1, 27, -1, 27, -1, 
          27, 27, 27, 45, 27}),
/* NxS[  47] */ // Shortest string "G"
      new Table(8, 21, -1, new short[] {47, 47, 47, 47, 47, 47, 
          47, 47, 47, 47, 47, 47, 47, 47, -1, -1, -1, -1, 47, 47, 47}),
/* NxS[  48] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {52, -1, 53}),
/* NxS[  49] */ new Table(0, 0, -1, null), // Shortest string "\t"
/* NxS[  50] */ // Shortest string "%"
      new Table(23, 18, 27, new short[] {-1, 27, 27, 27, 27, 27, 
          27, 27, 27, 27, 27, 27, 27, -1, 27, -1, 27, -1}),
/* NxS[  51] */ // Shortest string "\""
      new Table(25, 17, 138, new short[] {139, 138, 138, 138, -1, 138, 
          138, 138, 138, 138, 138, 13, 138, -1, 138, 13, -1}),
/* NxS[  52] */ // Shortest string "//"
      new Table(0, 5, 52, new short[] {-1, 52, 52, 52, -1}),
/* NxS[  53] */ new Table(0, 0, -1, null), // Shortest string "/*"
/* NxS[  54] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  55] */ // Shortest string "/"
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          56, 56, 56, 56, 56, 56, 56, -1, 32, -1, 70, -1}),
/* NxS[  56] */ // Shortest string "*"
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          56, 56, 56, 56, 56, 56, 56, -1, 56, -1, 56, -1}),
/* NxS[  57] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {54}),
/* NxS[  58] */ // Shortest string "\""
      new Table(23, 19, 58, new short[] {143, 58, 67, 58, 58, 58, 
          68, 58, 58, 58, 58, 58, 58, 13, 58, -1, 58, 13, 56}),
/* NxS[  59] */ // Shortest string "@"
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          61, 56, 56, 56, 56, 56, 56, -1, 56, -1, 56, -1}),
/* NxS[  60] */ // Shortest string "="
      new Table(23, 18, 60, new short[] {-1, 60, 60, 60, 60, 60, 
          60, 60, 60, 60, 60, 60, 60, -1, 60, -1, 60, -1}),
/* NxS[  61] */ // Shortest string "@\""
      new Table(23, 18, 61, new short[] {141, 61, 62, 61, 61, 61, 
          63, 61, 61, 61, 61, 61, 61, 141, 61, 141, 61, 141}),
/* NxS[  62] */ // Shortest string "@\"\\"
      new Table(23, 18, 61, new short[] {141, 61, 62, 61, 61, 61, 
          64, 61, 61, 61, 61, 61, 61, 141, 61, 141, 61, 141}),
/* NxS[  63] */ // Shortest string "@\"\""
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          61, 56, 56, 56, 56, 56, 56, -1, 56, -1, 56, -1}),
/* NxS[  64] */ // Shortest string "@\"\\\""
      new Table(23, 18, 61, new short[] {141, 61, 62, 61, 61, 61, 
          64, 61, 61, 61, 61, 61, 61, 141, 61, 141, 61, 141}),
/* NxS[  65] */ // Shortest string "@\"\t\""
      new Table(29, 1, -1, new short[] {141}),
/* NxS[  66] */ // Shortest string "@\"\t\\\""
      new Table(25, 5, 141, new short[] {142, 141, 141, 141, 66}),
/* NxS[  67] */ // Shortest string "\"\\"
      new Table(23, 18, 58, new short[] {143, 58, 58, 58, 58, 58, 
          58, 58, 58, 58, 58, 58, 58, -1, 58, 143, 58, -1}),
/* NxS[  68] */ // Shortest string "\"\""
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          56, 56, 56, 56, 56, 56, 56, -1, 56, -1, 56, -1}),
/* NxS[  69] */ new Table(0, 0, -1, null), // Shortest string "\"\x20\""
/* NxS[  70] */ // Shortest string "/*"
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          56, 56, 56, 56, 56, 56, 56, -1, 56, -1, 56, -1}),
/* NxS[  71] */ // Shortest string "^%"
      new Table(23, 18, 27, new short[] {-1, 27, 27, 27, 27, 27, 
          27, 27, 27, 27, 27, 27, 72, -1, 27, -1, 27, -1}),
/* NxS[  72] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  73] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  74] */ // Shortest string ""
      new Table(29, 14, 75, new short[] {78, 75, 75, 75, 75, 75, 
          75, -1, 75, 75, 76, -1, 75, 77}),
/* NxS[  75] */ // Shortest string "/"
      new Table(0, 5, 75, new short[] {-1, 75, 75, -1, -1}),
/* NxS[  76] */ // Shortest string "*"
      new Table(1, 1, -1, new short[] {80}),
/* NxS[  77] */ // Shortest string "%"
      new Table(0, 5, 75, new short[] {-1, 75, 75, 27, -1}),
/* NxS[  78] */ // Shortest string "\""
      new Table(25, 17, 78, new short[] {79, 78, 78, 78, 75, 78, 
          78, 78, 78, 78, 78, 13, 78, 75, 138, 13, 75}),
/* NxS[  79] */ // Shortest string "\"\\"
      new Table(0, 5, 78, new short[] {-1, 78, 78, 138, -1}),
/* NxS[  80] */ new Table(0, 0, -1, null), // Shortest string "*/"
/* NxS[  81] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {32, -1, 33}),
/* NxS[  82] */ // Shortest string "^%"
      new Table(22, 22, 90, new short[] {27, 90, 90, 90, 90, 90, 
          90, 27, 90, 90, 90, 27, 90, 92, 90, 27, 90, 90, 90, 90, 91, 27}),
/* NxS[  83] */ new Table(0, 0, -1, null), // Shortest string "{"
/* NxS[  84] */ // Shortest string "'"
      new Table(22, 20, 152, new short[] {-1, 152, 152, 153, 152, 152, 
          152, 152, 152, 152, 152, 152, 152, 152, -1, 152, -1, 152, -1, -1}),
/* NxS[  85] */ // Shortest string "\""
      new Table(25, 17, 85, new short[] {151, 85, 85, 85, 89, 85, 
          85, 85, 85, 85, 85, 13, 85, -1, 85, 13, -1}),
/* NxS[  86] */ // Shortest string "@"
      new Table(29, 1, -1, new short[] {149}),
/* NxS[  87] */ new Table(0, 0, -1, null), // Shortest string "}"
/* NxS[  88] */ // Shortest string "@\"\\\""
      new Table(25, 5, 149, new short[] {150, 149, 149, 149, 88}),
/* NxS[  89] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  90] */ // Shortest string "\t"
      new Table(22, 22, 90, new short[] {-1, 90, 90, 90, 90, 90, 
          90, -1, 90, 90, 90, -1, 90, -1, 90, -1, 90, 90, 90, 90, -1, -1}),
/* NxS[  91] */ new Table(0, 0, -1, null), // Shortest string "^%%"
/* NxS[  92] */ new Table(0, 0, -1, null), // Shortest string "^%}"
/* NxS[  93] */ // Shortest string "%"
      new Table(22, 22, 90, new short[] {27, 90, 90, 90, 90, 90, 
          90, 27, 90, 90, 90, 27, 90, 27, 90, 27, 90, 90, 90, 90, 27, 27}),
/* NxS[  94] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  95] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {32, -1, 33}),
/* NxS[  96] */ new Table(0, 0, -1, null), // Shortest string "*"
/* NxS[  97] */ // Shortest string "\r"
      new Table(0, 1, -1, new short[] {94}),
/* NxS[  98] */ // Shortest string "%"
      new Table(23, 18, 27, new short[] {-1, 27, 27, 27, 27, 27, 
          27, 27, 27, 27, 27, 27, 27, -1, 27, -1, 27, -1}),
/* NxS[  99] */ // Shortest string "\""
      new Table(25, 17, 138, new short[] {139, 138, 138, 138, -1, 138, 
          138, 138, 138, 138, 138, 13, 138, -1, 138, 13, -1}),
/* NxS[ 100] */ // Shortest string ""
      new Table(19, 28, 5, new short[] {8, 5, 5, 9, -1, 2, 
          2, 6, 5, 5, 10, 4, 11, 12, 2, 2, 4, -1, 1, -1, 2, -1, 
          2, 34, 4, 5, 6, 7}),
/* NxS[ 101] */ // Shortest string "^"
      new Table(19, 28, 5, new short[] {8, 5, 5, 9, -1, 2, 
          2, 6, 5, 5, 10, 4, 11, 12, 2, 2, 4, -1, 1, -1, 2, -1, 
          2, 3, 4, 5, 6, 7}),
/* NxS[ 102] */ // Shortest string "\"/"
      new Table(25, 17, 102, new short[] {103, 102, 102, 102, 14, 102, 
          102, 102, 102, 102, 102, 13, 102, -1, 102, 13, -1}),
/* NxS[ 103] */ // Shortest string "\"\\"
      new Table(0, 5, 102, new short[] {-1, 102, 102, 102, -1}),
/* NxS[ 104] */ // Shortest string "'/"
      new Table(22, 1, -1, new short[] {15}),
/* NxS[ 105] */ // Shortest string "'\\"
      new Table(19, 22, 104, new short[] {106, 107, 104, 104, 104, 104, 
          104, 106, 108, 109, 104, 104, 104, 104, 104, 104, 104, -1, 104, 104, 104, -1}),
/* NxS[ 106] */ // Shortest string "'\\0"
      new Table(19, 8, -1, new short[] {117, -1, -1, 15, -1, -1, 
          -1, 117}),
/* NxS[ 107] */ // Shortest string "'\\x"
      new Table(9, 18, -1, new short[] {116, 116, -1, 116, -1, 116, 
          -1, 116, -1, -1, 116, -1, 116, 15, -1, -1, -1, 116}),
/* NxS[ 108] */ // Shortest string "'\\u"
      new Table(9, 18, -1, new short[] {114, 114, -1, 114, -1, 114, 
          -1, 114, -1, -1, 114, -1, 114, 15, -1, -1, -1, 114}),
/* NxS[ 109] */ // Shortest string "'\\U"
      new Table(9, 18, -1, new short[] {110, 110, -1, 110, -1, 110, 
          -1, 110, -1, -1, 110, -1, 110, 15, -1, -1, -1, 110}),
/* NxS[ 110] */ // Shortest string "'\\U8"
      new Table(9, 18, -1, new short[] {111, 111, -1, 111, -1, 111, 
          -1, 111, -1, -1, 111, -1, 111, -1, -1, -1, -1, 111}),
/* NxS[ 111] */ // Shortest string "'\\U88"
      new Table(9, 18, -1, new short[] {112, 112, -1, 112, -1, 112, 
          -1, 112, -1, -1, 112, -1, 112, -1, -1, -1, -1, 112}),
/* NxS[ 112] */ // Shortest string "'\\U888"
      new Table(9, 18, -1, new short[] {113, 113, -1, 113, -1, 113, 
          -1, 113, -1, -1, 113, -1, 113, -1, -1, -1, -1, 113}),
/* NxS[ 113] */ // Shortest string "'\\U8888"
      new Table(9, 18, -1, new short[] {114, 114, -1, 114, -1, 114, 
          -1, 114, -1, -1, 114, -1, 114, -1, -1, -1, -1, 114}),
/* NxS[ 114] */ // Shortest string "'\\u8"
      new Table(9, 18, -1, new short[] {115, 115, -1, 115, -1, 115, 
          -1, 115, -1, -1, 115, -1, 115, -1, -1, -1, -1, 115}),
/* NxS[ 115] */ // Shortest string "'\\u88"
      new Table(9, 18, -1, new short[] {116, 116, -1, 116, -1, 116, 
          -1, 116, -1, -1, 116, -1, 116, -1, -1, -1, -1, 116}),
/* NxS[ 116] */ // Shortest string "'\\x8"
      new Table(9, 18, -1, new short[] {104, 104, -1, 104, -1, 104, 
          -1, 104, -1, -1, 104, -1, 104, -1, -1, -1, -1, 104}),
/* NxS[ 117] */ // Shortest string "'\\00"
      new Table(19, 8, -1, new short[] {104, -1, -1, -1, -1, -1, 
          -1, 104}),
/* NxS[ 118] */ // Shortest string "0x"
      new Table(9, 18, -1, new short[] {16, 16, -1, 16, -1, 16, 
          -1, 16, -1, -1, 16, -1, 16, -1, -1, -1, -1, 16}),
/* NxS[ 119] */ // Shortest string ""
      new Table(19, 27, 47, new short[] {2, 47, 47, 39, -1, 2, 
          2, 2, 47, 47, 40, 41, 2, 2, 2, 2, 41, -1, 1, -1, 2, -1, 
          2, 46, 37, 47, 2}),
/* NxS[ 120] */ // Shortest string "^"
      new Table(19, 27, 38, new short[] {2, 38, 38, 39, -1, 2, 
          2, 2, 38, 38, 40, 41, 2, 2, 2, 2, 41, -1, 1, -1, 2, -1, 
          2, 36, 37, 38, 2}),
/* NxS[ 121] */ // Shortest string "\"/"
      new Table(25, 17, 121, new short[] {122, 121, 121, 121, 42, 121, 
          121, 121, 121, 121, 121, 13, 121, -1, 121, 13, -1}),
/* NxS[ 122] */ // Shortest string "\"\\"
      new Table(0, 5, 121, new short[] {-1, 121, 121, 121, -1}),
/* NxS[ 123] */ // Shortest string "'/"
      new Table(22, 1, -1, new short[] {43}),
/* NxS[ 124] */ // Shortest string "'\\"
      new Table(19, 22, 123, new short[] {125, 126, 123, 123, 123, 123, 
          123, 125, 127, 128, 123, 123, 123, 123, 123, 123, 123, -1, 123, 123, 123, -1}),
/* NxS[ 125] */ // Shortest string "'\\0"
      new Table(19, 8, -1, new short[] {136, -1, -1, 43, -1, -1, 
          -1, 136}),
/* NxS[ 126] */ // Shortest string "'\\x"
      new Table(9, 18, -1, new short[] {135, 135, -1, 135, -1, 135, 
          -1, 135, -1, -1, 135, -1, 135, 43, -1, -1, -1, 135}),
/* NxS[ 127] */ // Shortest string "'\\u"
      new Table(9, 18, -1, new short[] {133, 133, -1, 133, -1, 133, 
          -1, 133, -1, -1, 133, -1, 133, 43, -1, -1, -1, 133}),
/* NxS[ 128] */ // Shortest string "'\\U"
      new Table(9, 18, -1, new short[] {129, 129, -1, 129, -1, 129, 
          -1, 129, -1, -1, 129, -1, 129, 43, -1, -1, -1, 129}),
/* NxS[ 129] */ // Shortest string "'\\U8"
      new Table(9, 18, -1, new short[] {130, 130, -1, 130, -1, 130, 
          -1, 130, -1, -1, 130, -1, 130, -1, -1, -1, -1, 130}),
/* NxS[ 130] */ // Shortest string "'\\U88"
      new Table(9, 18, -1, new short[] {131, 131, -1, 131, -1, 131, 
          -1, 131, -1, -1, 131, -1, 131, -1, -1, -1, -1, 131}),
/* NxS[ 131] */ // Shortest string "'\\U888"
      new Table(9, 18, -1, new short[] {132, 132, -1, 132, -1, 132, 
          -1, 132, -1, -1, 132, -1, 132, -1, -1, -1, -1, 132}),
/* NxS[ 132] */ // Shortest string "'\\U8888"
      new Table(9, 18, -1, new short[] {133, 133, -1, 133, -1, 133, 
          -1, 133, -1, -1, 133, -1, 133, -1, -1, -1, -1, 133}),
/* NxS[ 133] */ // Shortest string "'\\u8"
      new Table(9, 18, -1, new short[] {134, 134, -1, 134, -1, 134, 
          -1, 134, -1, -1, 134, -1, 134, -1, -1, -1, -1, 134}),
/* NxS[ 134] */ // Shortest string "'\\u88"
      new Table(9, 18, -1, new short[] {135, 135, -1, 135, -1, 135, 
          -1, 135, -1, -1, 135, -1, 135, -1, -1, -1, -1, 135}),
/* NxS[ 135] */ // Shortest string "'\\x8"
      new Table(9, 18, -1, new short[] {123, 123, -1, 123, -1, 123, 
          -1, 123, -1, -1, 123, -1, 123, -1, -1, -1, -1, 123}),
/* NxS[ 136] */ // Shortest string "'\\00"
      new Table(19, 8, -1, new short[] {123, -1, -1, -1, -1, -1, 
          -1, 123}),
/* NxS[ 137] */ // Shortest string ""
      new Table(29, 14, 49, new short[] {51, 49, 49, 49, 49, 49, 
          49, -1, 48, 49, 49, 49, 49, 50}),
/* NxS[ 138] */ // Shortest string "\"/"
      new Table(25, 17, 138, new short[] {139, 138, 138, 138, -1, 138, 
          138, 138, 138, 138, 138, 13, 138, -1, 138, 13, -1}),
/* NxS[ 139] */ // Shortest string "\"\\"
      new Table(0, 5, 138, new short[] {-1, 138, 138, 138, -1}),
/* NxS[ 140] */ // Shortest string ""
      new Table(23, 18, 56, new short[] {-1, 56, 56, 56, 56, 56, 
          58, 56, 56, 56, 59, 60, 56, 54, 55, -1, 56, 57}),
/* NxS[ 141] */ // Shortest string "@\"\t"
      new Table(25, 5, 141, new short[] {142, 141, 141, 141, 65}),
/* NxS[ 142] */ // Shortest string "@\"\t\\"
      new Table(25, 5, 141, new short[] {142, 141, 141, 141, 66}),
/* NxS[ 143] */ // Shortest string "\"\x20"
      new Table(25, 17, 143, new short[] {144, 143, 143, 143, 69, 143, 
          143, 143, 143, 143, 143, 13, 143, -1, 143, 13, -1}),
/* NxS[ 144] */ // Shortest string "\"\x20\\"
      new Table(0, 5, 143, new short[] {-1, 143, 143, 143, -1}),
/* NxS[ 145] */ // Shortest string "^"
      new Table(29, 14, 49, new short[] {51, 49, 49, 49, 49, 49, 
          49, -1, 48, 49, 49, 49, 49, 71}),
/* NxS[ 146] */ // Shortest string ""
      new Table(29, 14, 49, new short[] {51, 49, 49, 49, 49, 49, 
          73, -1, 48, 49, 49, 49, 49, 50}),
/* NxS[ 147] */ // Shortest string ""
      new Table(22, 22, 90, new short[] {84, 90, 90, 90, 90, 90, 
          90, 85, 90, 90, 90, 86, 90, 87, 90, 81, 90, 90, 90, 90, 93, 83}),
/* NxS[ 148] */ // Shortest string "^"
      new Table(22, 22, 90, new short[] {84, 90, 90, 90, 90, 90, 
          90, 85, 90, 90, 90, 86, 90, 87, 90, 81, 90, 90, 90, 90, 82, 83}),
/* NxS[ 149] */ // Shortest string "@\""
      new Table(25, 5, 149, new short[] {150, 149, 149, 149, 86}),
/* NxS[ 150] */ // Shortest string "@\"\\"
      new Table(25, 5, 149, new short[] {150, 149, 149, 149, 88}),
/* NxS[ 151] */ // Shortest string "\"\\"
      new Table(0, 5, 85, new short[] {-1, 85, 85, 85, -1}),
/* NxS[ 152] */ // Shortest string "'/"
      new Table(22, 1, -1, new short[] {89}),
/* NxS[ 153] */ // Shortest string "'\\"
      new Table(19, 22, 152, new short[] {154, 155, 152, 152, 152, 152, 
          152, 154, 156, 157, 152, 152, 152, 152, 152, 152, 152, -1, 152, 152, 152, -1}),
/* NxS[ 154] */ // Shortest string "'\\0"
      new Table(19, 8, -1, new short[] {165, -1, -1, 89, -1, -1, 
          -1, 165}),
/* NxS[ 155] */ // Shortest string "'\\x"
      new Table(9, 18, -1, new short[] {164, 164, -1, 164, -1, 164, 
          -1, 164, -1, -1, 164, -1, 164, 89, -1, -1, -1, 164}),
/* NxS[ 156] */ // Shortest string "'\\u"
      new Table(9, 18, -1, new short[] {162, 162, -1, 162, -1, 162, 
          -1, 162, -1, -1, 162, -1, 162, 89, -1, -1, -1, 162}),
/* NxS[ 157] */ // Shortest string "'\\U"
      new Table(9, 18, -1, new short[] {158, 158, -1, 158, -1, 158, 
          -1, 158, -1, -1, 158, -1, 158, 89, -1, -1, -1, 158}),
/* NxS[ 158] */ // Shortest string "'\\U8"
      new Table(9, 18, -1, new short[] {159, 159, -1, 159, -1, 159, 
          -1, 159, -1, -1, 159, -1, 159, -1, -1, -1, -1, 159}),
/* NxS[ 159] */ // Shortest string "'\\U88"
      new Table(9, 18, -1, new short[] {160, 160, -1, 160, -1, 160, 
          -1, 160, -1, -1, 160, -1, 160, -1, -1, -1, -1, 160}),
/* NxS[ 160] */ // Shortest string "'\\U888"
      new Table(9, 18, -1, new short[] {161, 161, -1, 161, -1, 161, 
          -1, 161, -1, -1, 161, -1, 161, -1, -1, -1, -1, 161}),
/* NxS[ 161] */ // Shortest string "'\\U8888"
      new Table(9, 18, -1, new short[] {162, 162, -1, 162, -1, 162, 
          -1, 162, -1, -1, 162, -1, 162, -1, -1, -1, -1, 162}),
/* NxS[ 162] */ // Shortest string "'\\u8"
      new Table(9, 18, -1, new short[] {163, 163, -1, 163, -1, 163, 
          -1, 163, -1, -1, 163, -1, 163, -1, -1, -1, -1, 163}),
/* NxS[ 163] */ // Shortest string "'\\u88"
      new Table(9, 18, -1, new short[] {164, 164, -1, 164, -1, 164, 
          -1, 164, -1, -1, 164, -1, 164, -1, -1, -1, -1, 164}),
/* NxS[ 164] */ // Shortest string "'\\x8"
      new Table(9, 18, -1, new short[] {152, 152, -1, 152, -1, 152, 
          -1, 152, -1, -1, 152, -1, 152, -1, -1, -1, -1, 152}),
/* NxS[ 165] */ // Shortest string "'\\00"
      new Table(19, 8, -1, new short[] {152, -1, -1, -1, -1, -1, 
          -1, 152}),
/* NxS[ 166] */ // Shortest string ""
      new Table(23, 20, 96, new short[] {-1, 96, 96, 96, 96, 96, 
          99, 96, 96, 96, 96, 96, 96, 94, 95, -1, 96, 97, 96, 98}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 36;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     internal Scanner(Stream file) {
            SetSource(file, -1); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     internal Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Token next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Token)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
// User-specified prolog to scan()
LexSpan comStart = null;
    LexSpan errStart = null;
    LexSpan errEnd   = null;
    int braceNestingLevel = 0;
// End, user-specified prolog
            try {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            switch (currentStart) {
                case 137:
yy_pop_state(); yyless(0);
                    break;
                case 74:
Error(53, comStart); /* This comment is unterminated */
                    break;
                case 147:
if (braceNestingLevel != 0)
                                  Error(55, TokenSpan()); 
                              yy_pop_state(); 
                              yyless(0); 
                              return (int)Token.codeEnd;
                    break;
            }
            if (yywrap())
                return (int)Token.EOF;
            break;
        case 1: // Recognized '{NotWh}',	Shortest string "/"
        case 2: // Recognized '{NotWh}',	Shortest string "*"
        case 3: // Recognized '{NotWh}',	Shortest string "^%"
        case 9: // Recognized '{NotWh}',	Shortest string "'"
        case 10: // Recognized '{NotWh}',	Shortest string "\""
        case 34: // Recognized '{NotWh}',	Shortest string "%"
        case 36: // In <TheRules> Recognized '{NotWh}',	Shortest string "^%"
        case 40: // In <TheRules> Recognized '{NotWh}',	Shortest string "\""
        case 46: // In <TheRules> Recognized '{NotWh}',	Shortest string "%"
        case 84: // In <CodeBlock> Recognized '{NotWh}',	Shortest string "'"
Error(57, TokenSpan());
            break;
        case 4: // Recognized '{OpChars}',	Shortest string "{"
return (int)(yytext[0]);
            break;
        case 5: // Recognized '{Ident}',	Shortest string "G"
        case 7: // Recognized '{Ident}',	Shortest string "F"
        case 17: // Recognized '{Ident}',	Shortest string "Fi"
        case 18: // Recognized '{Ident}',	Shortest string "Fie"
        case 19: // Recognized '{Ident}',	Shortest string "Fiel"
        case 20: // Recognized '{Ident}',	Shortest string "Field"
        case 21: // Recognized '{Ident}',	Shortest string "FieldO"
        case 22: // Recognized '{Ident}',	Shortest string "FieldOf"
        case 23: // Recognized '{Ident}',	Shortest string "FieldOff"
        case 24: // Recognized '{Ident}',	Shortest string "FieldOffs"
        case 25: // Recognized '{Ident}',	Shortest string "FieldOffse"
return (int)Token.ident;
            break;
        case 6: // Recognized '{Number}',	Shortest string "8"
        case 8: // Recognized '{Number}',	Shortest string "0"
yylval.iVal = ParseDecimal(yytext); return (int)Token.number;
            break;
        case 11: // Recognized '"("',	Shortest string "("
return (int)'(';
            break;
        case 12: // Recognized '")"',	Shortest string ")"
return (int)')';
            break;
        case 13: // Recognized '{BadStr}/[\r\n]',	Shortest string "\"\r"
_yytrunc(1); 
Error(58, TokenSpan());
            break;
        case 14: // Recognized '{LitStr}',	Shortest string "\"\""
return (int)Token.litstring;
            break;
        case 15: // Recognized '{LitChr}',	Shortest string "'/'"
return (int)Token.litchar;
            break;
        case 16: // Recognized '{HexNumber}',	Shortest string "0x8"
yylval.iVal = ParseHexaDec(yytext); return (int)Token.number;
            break;
        case 26: // Recognized '"FieldOffset"',	Shortest string "FieldOffset"
return (int)Token.fieldOffset;
            break;
        case 27: // Recognized '%{NotWh}',	Shortest string "%/"
Error(50, TokenSpan());
            break;
        case 28: // Recognized '^%%',	Shortest string "^%%"
yy_clear_stack();
                              BEGIN(TheRules); 
                              yy_push_state(ShouldBeBlank); errStart = null;
                              return (int)Token.kwPCPC;
            break;
        case 29: // Recognized '^%\{',	Shortest string "^%{"
yy_push_state(Prolog); 
                              yy_push_state(ShouldBeBlank); errStart = null;
                              return (int)Token.kwLbrace;
            break;
        case 30: // Recognized '^%{Ident}',	Shortest string "^%G"
{
                                  Token kWord = GetKeyword(yytext); 
                                  if (kWord == Token.kwOutput || kWord == Token.kwImportTokens)
                                      BEGIN(GetPath);
                                  return (int)kWord;
                              }
            break;
        case 31: // Recognized '^%\}',	Shortest string "^%}"
return (int)Token.kwRbrace; /* But a syntax error! */
            break;
        case 32: // Recognized '{OneLineCmnt}',	Shortest string "//"
/* skip */
            break;
        case 33: // Recognized '{CmntStrt}',	Shortest string "/*"
        case 70: // In <GetPath> Recognized '{CmntStrt}',	Shortest string "/*"
yy_push_state(Comment); 
                              comStart = TokenSpan(); 
                              /* And no token returned */
            break;
        case 35: // Recognized '\%{Ident}',	Shortest string "%G"
{   // An error, but attempt recovery
                                  Token kWord = GetKeyword(yytext); 
                                  if (kWord != Token.errTok)
                                      Error(59, TokenSpan());
                                  if (kWord == Token.kwOutput || kWord == Token.kwImportTokens)
                                      BEGIN(GetPath);
                                  return (int)kWord;
                              }
            break;
        case 37: // In <TheRules> Recognized '\{',	Shortest string "{"
yy_push_state(Action); 
                        braceNestingLevel = 1; 
                        return (int)'{';
            break;
        case 38: // In <TheRules> Recognized '^{Ident}',	Shortest string "^G"
return (int)Token.anchoredSymbol;
            break;
        case 39: // In <TheRules> Recognized '\'',	Shortest string "'"
Error(58, TokenSpan());
            break;
        case 41: // In <TheRules> Recognized '{OpChars}',	Shortest string ","
return (int)(yytext[0]);
            break;
        case 42: // In <TheRules> Recognized '{LitStr}',	Shortest string "\"\""
return (int)Token.litstring;
            break;
        case 43: // In <TheRules> Recognized '{LitChr}',	Shortest string "'/'"
return (int)Token.litchar;
            break;
        case 44: // In <TheRules> Recognized '^%%',	Shortest string "^%%"
yy_clear_stack();
                        BEGIN(TheEpilog); 
                        yy_push_state(ShouldBeBlank); errStart = null;
                        return (int)Token.kwPCPC;
            break;
        case 45: // In <TheRules> Recognized '\%{Ident}',	Shortest string "%G"
return (int)GetKeyword(yytext);
            break;
        case 47: // In <TheRules> Recognized '{Ident}',	Shortest string "G"
return (int)Token.ident;
            break;
        case 48: // In <TheEpilog> Recognized '.',	Shortest string "/"
        case 49: // In <TheEpilog> Recognized '.',	Shortest string "\t"
        case 50: // In <TheEpilog> Recognized '.',	Shortest string "%"
        case 51: // In <TheEpilog> Recognized '.',	Shortest string "\""
        case 71: // In <Prolog> Recognized '.',	Shortest string "^%"
yy_push_state(CodeBlock); yyless(0); return (int)Token.codeStart;
            break;
        case 52: // In <TheEpilog> Recognized '{OneLineCmnt}',	Shortest string "//"
yy_push_state(CodeBlock);  
                              return (int)Token.codeStart;
            break;
        case 53: // In <TheEpilog> Recognized '{CmntStrt}',	Shortest string "/*"
yy_push_state(CodeBlock); 
                              yy_push_state(Comment); 
                              comStart = TokenSpan(); 
                              return (int)Token.codeStart;
            break;
        case 54: // In <GetPath> Recognized '{Eol}',	Shortest string ""
        case 57: // In <GetPath> Recognized '{Eol}',	Shortest string "\r"
BEGIN(0);
            break;
        case 55: // In <GetPath> Recognized '{NotWh}+',	Shortest string "/"
        case 56: // In <GetPath> Recognized '{NotWh}+',	Shortest string "*"
        case 58: // In <GetPath> Recognized '{NotWh}+',	Shortest string "\""
        case 59: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@"
        case 61: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@\""
        case 62: // In <GetPath> Recognized '{NotWh}+',	Shortest string "@\"\\"
        case 67: // In <GetPath> Recognized '{NotWh}+',	Shortest string "\"\\"
return (int)Token.filePath;
            break;
        case 60: // In <GetPath> Recognized '={NotWh}*',	Shortest string "="
yyless(1); return (int)'=';
            break;
        case 63: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\""
        case 64: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\\\""
        case 65: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\t\""
        case 66: // In <GetPath> Recognized '{VrbStr}',	Shortest string "@\"\t\\\""
return (int)Token.verbatim;
            break;
        case 68: // In <GetPath> Recognized '{LitStr}',	Shortest string "\"\""
        case 69: // In <GetPath> Recognized '{LitStr}',	Shortest string "\"\x20\""
return (int)Token.litstring;
            break;
        case 72: // In <Prolog> Recognized '^%\}',	Shortest string "^%}"
if (braceNestingLevel != 0) {
                                  Error(55, TokenSpan()); braceNestingLevel = 0;
                              }
                              else {
                                  yy_pop_state(); return (int)Token.kwRbrace; 
                              }
            break;
        case 73: // In <Action> Recognized '\}',	Shortest string "}"
yy_pop_state(); return (int)'}';
            break;
        case 74: // In <Comment> Recognized '{ABStar}',	Shortest string ""
        case 75: // In <Comment> Recognized '{ABStar}',	Shortest string "/"
        case 76: // In <Comment> Recognized '\*',	Shortest string "*"
        case 77: // In <Comment> Recognized '{ABStar}',	Shortest string "%"
        case 78: // In <Comment> Recognized '{ABStar}',	Shortest string "\""
        case 79: // In <Comment> Recognized '{ABStar}',	Shortest string "\"\\"
/* skip */
            break;
        case 80: // In <Comment> Recognized '{CmntEnd}',	Shortest string "*/"
yy_pop_state();
                         // If comment has obscured one or more EOL then ...  
                         if (YY_START == ShouldBeBlank) {
                             if (errStart != null) {
                                 Error(54, errStart.Merge(errEnd));
                                 errStart = null;
                             } else if (lNum > comStart.startLine) 
                                 yy_pop_state();
                         }
                         /* And no token returned */
            break;
        case 81: // In <CodeBlock> Recognized '\/',	Shortest string "/"
        case 82: // In <CodeBlock> Recognized '\%',	Shortest string "^%"
        case 86: // In <CodeBlock> Recognized '@',	Shortest string "@"
        case 88: // In <CodeBlock> Recognized '{VrbStr}',	Shortest string "@\"\\\""
        case 89: // In <CodeBlock> Recognized '{LitStr}',	Shortest string "\"\""
        case 90: // In <CodeBlock> Recognized '\%{CodeSkip}+',	Shortest string "\t"
        case 93: // In <CodeBlock> Recognized '\%',	Shortest string "%"
/* skip */
            break;
        case 83: // In <CodeBlock> Recognized '\{',	Shortest string "{"
braceNestingLevel++;
            break;
        case 85: // In <CodeBlock> Recognized '{BadStr}',	Shortest string "\""
Error(58, TokenSpan());
            break;
        case 87: // In <CodeBlock> Recognized '\}',	Shortest string "}"
if (braceNestingLevel == 0 && 
                                       yy_top_state() == Action) {
                                  yy_pop_state();
                                  yyless(0);
                                  return (int)Token.codeEnd;
                              }
                              else
                                  braceNestingLevel--;
            break;
        case 91: // In <CodeBlock> Recognized '^%%',	Shortest string "^%%"
Error( 60, TokenSpan() );
                                for ( ; ; ) {
                                  switch (YY_START)
                                  {
                                    case INITIAL: 
                                       return (int)Token.kwPCPC;
                                    case TheRules: 
                                       return (int)Token.kwPCPC;
                                    case TheEpilog:
                                    case CodeBlock: // just skip the token and continue ...
                                       Error( 61, TokenSpan() );
                                       return yylex();
                                    default: 
                                        yy_pop_state(); break; 
                                  }
                               }
            break;
        case 92: // In <CodeBlock> Recognized '^%\}',	Shortest string "^%}"
if (yy_top_state() != Prolog) {
                                  Error(56, TokenSpan()); yy_clear_stack(); BEGIN(Prolog);
                              } else if (braceNestingLevel != 0) {
                                  Error(55, TokenSpan());
                              } else {
                                  yy_pop_state();
                              } 
                              yyless(0); return (int)Token.codeEnd;
            break;
        case 94: // In <ShouldBeBlank> Recognized '{Eol}',	Shortest string ""
        case 97: // In <ShouldBeBlank> Recognized '{Eol}',	Shortest string "\r"
if (errStart != null)
                                  Error(54, errStart.Merge(errEnd)); 
                              yy_pop_state();
            break;
        case 95: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "/"
        case 96: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "*"
        case 98: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "%"
        case 99: // In <ShouldBeBlank> Recognized '{NotWh}',	Shortest string "\""
{
                                LexSpan cSpan = TokenSpan(); /* Only white space goes here */
                                errEnd = cSpan;
                                if (errStart == null) errStart = cSpan;
                              }
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
            } // end try
            finally {
// User-specified epilog to scan()
yylloc = new LexSpan(tokLin, tokCol, tokELin, tokECol, tokPos, tokEPos, buffer);
// End, user-specified epilog
            } // end finally
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
#region UserCodeSection

/* User Code is all in ScanHelper.cs */

#endregion
    } // end class $Scanner


} // end namespace
